### ISSUE TITLE
v4 breaks prettier blob formatting

### ISSUE THREAD

**Issue by sitch** [IanVS/prettier-plugin-sort-imports#103]
When using prettier to directly format a string, i.e.:

```ts
import prettier from "prettier"

prettier.format(content, options)
```

This raises an error because `filePath` isn't always available for the check:

https://github.com/IanVS/prettier-plugin-sort-imports/blob/e20a9fd14a2d261d6c8602675ff0183010098b26/src/utils/normalize-plugin-options.ts#L91

Should be able to just use an option chain on that value `filepath?.endsWith(".ts")`

**Comment by IanVS** [comment]
Yeah that sounds reasonable, would you like to submit a PR?

**Comment by thebuilder** [comment]
Also ran into this. Came around it by removing the `plugins` from options for now. (Which also disables this plugin).

Was also thinking the optional chain is the right fix. 👍

**Comment by sitch** [comment]
@IanVS happy to send a PR.
