### ISSUE TITLE
[Feature] Allow manual configuration of line breaks

### ISSUE THREAD

**Issue by IanVS** [IanVS/prettier-plugin-sort-imports#11]
**Is your feature request related to a problem?**
See https://github.com/trivago/prettier-plugin-sort-imports/issues/36

**Describe the solution you'd like**
I think the solution in https://github.com/trivago/prettier-plugin-sort-imports/pull/42 is pretty smart.  It does not require a new option, but gives some flexibility for folks who want to specify new lines between specific groups.

**Describe alternatives you've considered**
We could wait until the upstream project merges this, but it seems a little unlikely at this point.

@blutorange, what do you think of this approach?

**Comment by blutorange** [comment]
So if I understand this correctly, `importOrderSeparation: true` already allows import groups to be separated, but this suggestion allows people to separate some, but not all import groups? Tbh I personally don't understand why people want so much control over how imports are sorted, but this solution does look like a good extension of an existing mechanism.
