### ISSUE TITLE
Breaks with Prettier v3.0.3

### ISSUE THREAD

**Issue by DeeJEarl88** [IanVS/prettier-plugin-sort-imports#121]
**Your Environment**
-   **Prettier version**: 3.0.3
-   **node version**: 18
-   **package manager**: yarn@2
-   **IDE**: VScode

**Describe the bug**
- Prettier doesn't recognize this plugin and it's additional settings

**To Reproduce**
- Install the latest versions of prettier and this package
- Setup prettier config to have `importOrder`
- Run prettier formatting and receive warning

**Expected behavior**
- Formatting to happen as it normally would

**Screenshots, code sample, etc**
![image](https://github.com/IanVS/prettier-plugin-sort-imports/assets/52415442/ea64f76d-4de8-4901-a43c-e2c4b04587f3)

**Configuration File (.prettierrc)**
{
  "endOfLine": "auto",
  "printWidth": 120,
  "semi": true,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "all",
  "importOrder": ["<BUILTIN_MODULES>", "<THIRD_PARTY_MODULES>", "", "^@homespring-services/common(/.*)?$", "^[./]"]
}

**Contribute to @ianvs/prettier-plugin-sort-imports**

-   [ ] I'm willing to fix this bug 🥇

**Comment by IanVS** [comment]
Prettier 3 requires you to specify your plugins explicitly.  See https://github.com/IanVS/prettier-plugin-sort-imports#usage
