### ISSUE TITLE
'use client' is a separate line, it would be good to have it with node_modules import

### ISSUE THREAD

**Issue by ivanafanasyeu** [IanVS/prettier-plugin-sort-imports#144]
**Is your feature request related to a problem?**
```tsx
'use client';

import { useParams } from 'next/navigation';
```

**Describe the solution you'd like**
```tsx
'use client';
import { useParams } from 'next/navigation';
```

**Describe alternatives you've considered**
no alternatives, it would be good to add it somehow into regexp groups or something

**Additional context**
It's a feature from new react

**Comment by IanVS** [comment]
Hello,

Thanks for the suggestion.  As I'm sure you know, prettier itself is very opinionated about the formatting it does, and while this plugin does have a number of options, we also are opinionated about some styling decisions.  This is one case where we have decided there should be an empty line after directives, to separate them from imports.  So we won't be adding an option to adjust this behavior.
