### ISSUE TITLE
Empty line between some groups are not working

### ISSUE THREAD

**Issue by ivanafanasyeu** [IanVS/prettier-plugin-sort-imports#145]
**Your Environment**

-   **Prettier version**: 3.2.5
-   **node version**: 21.1.0
-   **package manager**: [yarn@3.8.0]
-   **IDE**: [VScode]

**Describe the bug**
```js
//.prettier.rc
//...
   "importOrder": ["<BUILTIN_MODULES>", "<THIRD_PARTY_MODULES>", "^@", "^[../]", "", "^[./]", "", "<TYPES>"],
  //...
```

Result
```
'use client';

import { translateSegment } from '../utils';
import { useLocale } from './useLocale';
```

**To Reproduce**

1. Just install the package in next.js project and add config from the bug description.

**Expected behavior**
Separate line between "../" and "./"

**Screenshots, code sample, etc**
<img width="649" alt="Screenshot 2024-02-06 at 10 38 54" src="https://github.com/IanVS/prettier-plugin-sort-imports/assets/25664253/49ad41bb-8121-47a6-b916-40501f30253d">

<img width="795" alt="Screenshot 2024-02-06 at 10 39 09" src="https://github.com/IanVS/prettier-plugin-sort-imports/assets/25664253/9f9f6c0f-d98e-487c-8019-f62f1e6d01a0">

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**

```
{
    "$schema": "https://json.schemastore.org/prettierrc",
    "arrowParens": "always",
    "semi": true,
    "quoteProps": "consistent",
    "bracketSameLine": true,
    "endOfLine": "lf",
    "singleAttributePerLine": true,
    "printWidth": 120,
    "tabWidth": 4,
    "singleQuote": true,
    "useTabs": false,
    "plugins": ["@ianvs/prettier-plugin-sort-imports"],
    "importOrder": ["<BUILTIN_MODULES>", "<THIRD_PARTY_MODULES>", "^@", "^[../]", "", "^[./]", "", "<TYPES>"],
    "importOrderParserPlugins": ["typescript", "jsx", "decorators-legacy"]
}
```

**Error log**
-

**Contribute to @ianvs/prettier-plugin-sort-imports**

-   [ ] I'm willing to fix this bug 🥇

**Comment by IanVS** [comment]
Hi, thanks for the issue.  I think the problem is that your regex is not what you expect.

The regex `[../]` will match the character `.` or `/` (see https://regex101.com/r/Hh40PX/2)

What you want is `^\.\.\/`, which matches the pattern `../` exactly, and only at the start.  (https://regex101.com/r/Hh40PX/3).

Give that a shot and let me know if you're still having problems.

**Comment by IanVS** [comment]
You need to also remove the `[]` characters, as I showed in the example in my link.

**Comment by IanVS** [comment]
And if json is not happy, you may need to convert it to a javascript file.  https://prettier.io/docs/en/configuration

**Comment by ivanafanasyeu** [comment]
Yeah, with .mjs it's working
