### ISSUE TITLE
Error: unknown type: "ChainExpression"

### ISSUE THREAD

**Issue by rawand-faraidun** [IanVS/prettier-plugin-sort-imports#148]
This error is ta prettier error in general: `Error: unknown type: "ChainExpression"`, but i get it when using prettier with this package and has no problem when removing it, the error seems to be happening because of optional chaining operator `?` like `config?.defaultLocale`

**Environment**

-   **Prettier version**: ^3.2.4
-   **node version**: v20.10.0
-   **package manager**: PNPM: 8.12.0
-   **IDE**: CLI

**Describe the bug**

i believe it is related to this problem in prettier [https://github.com/prettier/prettier/pull/13735](https://github.com/prettier/prettier/pull/13735), but it is fixed in prettier but somehow still happens with this package, to see the files I have a public repository that has this problem [https://github.com/rawand-faraidun/linguify](https://github.com/rawand-faraidun/linguify), it happens when using command line prettier. can be tested on files like [validate.ts](https://github.com/rawand-faraidun/linguify/blob/main/lib/validation/validate.ts), [AddKey.tsx](https://github.com/rawand-faraidun/linguify/blob/main/src/client/src/components/sections/AddKey.tsx)

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**

```json
// .prettierrc.json

{
  "trailingComma": "none",
  "tabWidth": 2,
  "useTabs": false,
  "semi": false,
  "singleQuote": true,
  "arrowParens": "avoid",
  "printWidth": 125,
  "endOfLine": "crlf",
  "overrides": [
    {
      "files": "*.tsx",
      "options": {
        "tabWidth": 2,
        "useTabs": false,
        "jsxSingleQuote": false
      }
    },
    {
      "files": "*.css",
      "options": {
        "singleQuote": false
      }
    }
  ],
  "importOrder": [
    "<BUILTIN_MODULES>",
    "fs",
    "express",
    "^(react/(.*)$)|^(react$)",
    "^(react-router-dom/(.*)$)|^(react-router-dom$)",
    "<THIRD_PARTY_MODULES>",
    "^@/(.*)$",
    "^[.]",
    "^@lib",
    ".css$"
  ],
  "plugins": ["@ianvs/prettier-plugin-sort-imports"]
}
```

**Contribute to @ianvs/prettier-plugin-sort-imports**

-   [ ] I'm willing to fix this bug 🥇

**Comment by fbartho** [comment]
This package depends on your node_modules-installed version of prettier.

This means that even if globally you have a higher version, you might have a lower version in your node_modules dir! Can you verify your lockfile or node_modules to figure out what version of prettier you have installed *locally* for that project?

A clean install or a force upgrade of prettier may resolve the issue!

If it still occurs, it'd be helpful to get the full call stack when the error appears.

**Comment by rawand-faraidun** [comment]
@fbartho you were right, the problem was because of globally installed prettier

thanks
