### ISSUE TITLE
Feature: Biome Integration

### ISSUE THREAD

**Issue by fbartho** [IanVS/prettier-plugin-sort-imports#149]
I heard about [Biome](https://biomejs.dev/) today, which is a Prettier replacement written in Rust, with a focus on speed.

It boasts over 97% prettier compatibility (but I couldn’t figure out what exactly didn’t work), and it’d be super interesting if that means plugins can be hosted by it.

I haven’t had a chance to read the docs, but I figured you, @IanVS, might be interested in checking it out.

It wouldn’t surprise me if we cannot be hosted by it, or that we’d want to fork this lib for proper integration, but I figured I’d post this ticket here just in case.

**Comment by IanVS** [comment]
As of today, Biome does not have support for plugins.  But!  There's a recent RFC to discuss adding such a capability: https://github.com/biomejs/biome/discussions/1762

And, if you'd like to see a chat I did with the creator of Biome and one of the maintainers of typescript-eslint, it's up at https://youtu.be/cGHCdqnT05Q?si=DC5FbHW0A7O5dgga.

**Comment by IanVS** [comment]
Thanks for bringing this up, but I don't personally have the time to explore such an integration.  If anyone else wants to, feel free!
