### ISSUE TITLE
Import without parameters 

### ISSUE THREAD

**Issue by Natchii59** [IanVS/prettier-plugin-sort-imports#150]
**Describe the solution you'd like**
It would be nice to be able to put imports without parameters in the plugin configuration.

**Additional context**
<img width="380" alt="Capture d’écran 2024-02-20 à 15 25 17" src="https://github.com/IanVS/prettier-plugin-sort-imports/assets/96394660/b8e17aae-f106-4751-b10d-92d4872b0834">

**Comment by IanVS** [comment]
Please see the discussion in https://github.com/IanVS/prettier-plugin-sort-imports/issues/51 as to why we do not sort these kinds of imports.
