### ISSUE TITLE
Pragma & Comment handling

### ISSUE THREAD

**Issue by therealgilles** [IanVS/prettier-plugin-sort-imports#166]
**Your Environment**

-   **Prettier version**: 3.2.5
-   **node version**: v20.5.0
-   **package manager**: npm@10.5.0
-   **IDE**: VScode

**Describe the bug**
Here is the code:
```TSX
/** @jsxImportSource @emotion/react */
'use client'
/**
 * Filename.tsx
 *
 */

import { ... } from '...'
```

It is transformed by this plugin as follows:
```TSX
/** @jsxImportSource @emotion/react */
'use client'

/**
 * Filename.tsx
 *
 */
import { ... } from '...'
```

and that seems unexpected.

**To Reproduce**
See above.

**Expected behavior**
The comment is left where it was. The plugin honor the empty line specified at the top of `importOrder`.

**Screenshots, code sample, etc**
See above.

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**
Here is the `importOrder`:
```TSX
  importOrder: [
    '',
    '<BUILT_IN_MODULES>',
    '<THIRD_PARTY_MODULES>',
    '',
    '^@(/.*)$',
    '^(?!.*[.]css$)[./].*$',
    '.css$',
  ],
```

Not sure exactly how to fix this.

**Comment by fbartho** [comment]
If you don't want a gap after `'use client';` -- you can remove your blank group from the front of your `importOrder` array:
```diff
 importOrder: [
-    '',
    '<BUILT_IN_MODULES>',
    '<THIRD_PARTY_MODULES>',
    '',
    '^@(/.*)$',
    '^(?!.*[.]css$)[./].*$',
    '.css$',
  ],
  ```
  
  Does that do what you want @therealgilles?

**Comment by therealgilles** [comment]
The expected the code to stay like this:
```TSX
/** @jsxImportSource @emotion/react */
'use client'
/**
 * Filename.tsx
 *
 */

import { ... } from '...'
```

**Comment by IanVS** [comment]
My guess is that the `'use client'` pragma is breaking our "top of file" comment detection, and the jsdoc block is being treated as a leading comment on the first import.  We can try looking into this, but it's not going to be a super-high priority.

**Comment by therealgilles** [comment]
It's alright, I'll close this issue. Thank you for taking the time to assist me and giving my issue some thoughts.
With RSC, pragmas are going to become more common.
