### ISSUE TITLE
Type `RequiredOptions` in "prettier" module is not augmented with plugin options

### ISSUE THREAD

**Issue by jeremy-code** [IanVS/prettier-plugin-sort-imports#169]
**Your Environment**

-   **Prettier version**: 2.x.x
-   **node version**: v22.2.0
-   **package manager**: pnpm@9.1.2
-   **IDE**: VSCode (v1.89.1)

**Describe the bug**

TypeScript [module augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation) with the `"prettier"` module is not supported, meaning using JSDoc types for the plugin options are not correctly denoted in IDEs (and presumably when the prettier config are typed-checked with TypeScript).

**To Reproduce**

1. Open an IDE with TypeScript support.
2. See what type is given for any of the plugin options (e.g. `importOrder`, `importOrderTypeScriptVersion`, `importOrderParserPlugins`).
3. See it is based on what is inferred (usually `never[]` or `string[]`) and does not have the corresponding JSDoc comments.

**Expected behavior**

As shown in the second screenshot, I expect the correct types for the options to be given, but also when using the `Config` type from `prettier` (first screenshot). It's a minor quibble, since `import("@ianvs/prettier-plugin-sort-imports").PrettierConfig` is also provided, but that is a bit long.

I believe the code that would make this possible something like:

```js
// @ianvs/prettier-plugin-sort-imports/types/index.d.ts
declare module 'prettier' {
  interface RequiredOptions extends PluginConfig {}
}
```

but when I attempted the trivial fix, I had some conflicts with the types in `src/types.ts`. I will take a look further, but I wanted to let you know beforehand.

**Screenshots, code sample, etc**

![image](https://github.com/IanVS/prettier-plugin-sort-imports/assets/43259194/d1c6890a-698c-46ca-adfa-cc59780ab9e2)

![image](https://github.com/IanVS/prettier-plugin-sort-imports/assets/43259194/4f437e17-fbc8-4306-9847-76bafe25e374)

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**

```js
// .prettierrc.js
/** @type {import(prettier").Config} */
module.exports = {
  plugins: [require("@ianvs/prettier-plugin-sort-imports")],
  importOrder: [], // never[], but should be string[] | undefined
};
```

**Error log**

No errors.

**Contribute to @ianvs/prettier-plugin-sort-imports**

-   [x] I'm willing to fix this bug 🥇

**Comment by IanVS** [comment]
Thanks for the issue.  I would happily accept a PR that addresses this!
