### ISSUE TITLE
Error when using explicit resource management

### ISSUE THREAD

**Issue by skycoop** [IanVS/prettier-plugin-sort-imports#182]
**Your Environment**

-  **Plugin version**: 4.3.1
-   **Prettier version**:  3.3.3
-   **node version**:  20.17.0
-   **package manager**: pnpm@9.11.0
-   **IDE**: VScode

**Describe the bug**

When using keywords from [Explicit Resource Management](https://github.com/tc39/proposal-explicit-resource-management) (i.e. `using`/`await using`), this plugin causes prettier to fail.

**To Reproduce**

Use `using`/`await using` in any file.

**Expected behavior**

No error

**Screenshots, code sample, etc**

```ts
# app/.server/utils/action.ts
...
await using fileStorage = new TempFileStorage("spanda-");
...
```

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**

```js
/** @type {import("prettier").Config} */
export default {
  plugins: [
    "@ianvs/prettier-plugin-sort-imports",
    "prettier-plugin-tailwindcss",
  ],
  importOrder: [
    "<BUILTIN_MODULES>",
    "",
    "^@remix-run/",
    "^react$",
    "<THIRD_PARTY_MODULES>",
    "",
    "^@\\/.*$",
    "^[.]",
    "",
    "^(?!.*[.]css$)[./].*$",
    ".css$",
  ],
  importOrderTypeScriptVersion: "5.0.0",
};
```

**Error log**

```
app/.server/utils/action.ts
[error] app/.server/utils/action.ts: SyntaxError: This experimental syntax requires enabling the parser plugin: "explicitResourceManagement". (119:4)
```

**Contribute to @ianvs/prettier-plugin-sort-imports**

-   [x] I'm willing to fix this bug 🥇

**Comment by skycoop** [comment]
Ah ok I found that adding `explicitResourceManagement` to `importOrderParserPlugins` fixes it. I half wonder if the error message could be improved to suggest this?

**Comment by IanVS** [comment]
Glad you figured it out.  Feel free to try improving the error message, but it's coming from babel, so I think you'd need to make a PR there.  It should probably at least be something like `This experimental syntax requires enabling the _babel_ parser plugin ...`
