### ISSUE TITLE
Order expected

### ISSUE THREAD

**Issue by kratess** [IanVS/prettier-plugin-sort-imports#187]
**Describe the bug**
**To Reproduce**

```
import Image from "next/image";

import ResourceInfo from "@partials/resource/ResourceInfo";

import "@styles/content.css";

import React from "react";
```

**Expected behavior**

```
import React from "react";

import Image from "next/image";

import ResourceInfo from "@partials/resource/ResourceInfo";

import "@styles/content.css";
```

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**

```
    "importOrder": [
        "^(react/(.*)$)|^(react$)",
        "",
        "next",
        "",
        "@partials",
        "",
        "@components",
        "",
        "<THIRD_PARTY_MODULES>",
        "",
        "^@redux/store$",
        "^react-redux$",
        "^redux$",
        "^@redux/slices",
        "",
        "@lib",
        "",
        "@public",
        "@icons",
        "",
        "^[./]"
    ],
```

**Comment by fbartho** [comment]
hey @kratess! We've run into this a few times before:

- https://github.com/IanVS/prettier-plugin-sort-imports/issues/181#issuecomment-2322954534
- https://github.com/IanVS/prettier-plugin-sort-imports/issues/186#issuecomment-2407259849

Quick summary, we can't move imports across an import meant for side-effects -- and your CSS import is one of those .

**Comment by kratess** [comment]
I see... so the side-effect is given by imports that no import a specific module along them? like the css in my imports? So those cases must be managed manaually. Am I right?

But i have another question. If all modules that do not import a module must maintain the order why don't create a placeholder for them but still maintaining the order?

Something like: "<NO_MODULES>"

So even importing something like this:

```
...

import "@styles/import1.css";
import "@styles/import2.css";

import "@styles/import3.css";
import {a} from "...";

import "@styles/import4.css";

import "@styles/import5.css";
```

will result in something like this:

```
...
import {a} from "...";

import "@styles/import1.css";
import "@styles/import2.css";
import "@styles/import3.css";
import "@styles/import4.css";
import "@styles/import5.css";
```

**Comment by kratess** [comment]
@fbartho @IanVS

**Comment by fbartho** [comment]
We can't move them at all, because that might change how the import {a} was imported, like throwing an exception because a global might be missing after you reordered those imports. We have to be somewhat conservative in this case because we cannot break the user's code with what they expect to be a safe and trivial formatting change.
