### ISSUE TITLE
Is `@babel/core` unused and can it be removed?

### ISSUE THREAD

**Issue by cobaltt7** [IanVS/prettier-plugin-sort-imports#189]
**Your Environment**

-   **Prettier version**: 3.3.3
-   **node version**: 22.10.0
-   **package manager**: npm@9
-   **IDE**: VSCode

**Describe the bug**

`@babel/core` [does not seem to be used at all](https://github.com/search?q=repo%3AIanVS%2Fprettier-plugin-sort-imports+%22%40babel%2Fcore%22&type=code) in the package, and I believe it is unnecessarily adding 21MB / 20 dependencies to the bundle. See the package's dependency graph [with](https://npmgraph.js.org/?q=%40ianvs%2Fprettier-plugin-sort-imports#select=exact%3A%40ianvs%2Fprettier-plugin-sort-imports%404.3.1) and [without](https://npmgraph.js.org/?q=-%404.3.1#packages=%5B%7B%22dependencies%22%3A%7B%22%40babel%2Fgenerator%22%3A%22%5E7.23.6%22%2C%22%40babel%2Fparser%22%3A%22%5E7.24.0%22%2C%22%40babel%2Ftraverse%22%3A%22%5E7.24.0%22%2C%22%40babel%2Ftypes%22%3A%22%5E7.24.0%22%2C%22semver%22%3A%22%5E7.5.2%22%7D%2C%22devDependencies%22%3A%7B%22%40types%2Fbabel__generator%22%3A%22%5E7.6.8%22%2C%22%40types%2Fbabel__traverse%22%3A%22%5E7.20.5%22%2C%22%40types%2Fnode%22%3A%22%5E18.15.13%22%2C%22%40types%2Fprettier%22%3A%22%5E3.0.0%22%2C%22%40types%2Fsemver%22%3A%22%5E7.5.3%22%2C%22%40vue%2Fcompiler-sfc%22%3A%223.4.21%22%2C%22cross-env%22%3A%22%5E7.0.3%22%2C%22prettier%22%3A%22%5E3.0.3%22%2C%22prettier-plugin-astro%22%3A%22%5E0.14.0%22%2C%22typescript%22%3A%225.2.2%22%2C%22vitest%22%3A%22%5E0.34.5%22%7D%2C%22license%22%3A%22Apache-2.0%22%2C%22name%22%3A%22-%22%2C%22peerDependencies%22%3A%7B%22%40vue%2Fcompiler-sfc%22%3A%222.7.x+%7C%7C+3.x%22%2C%22prettier%22%3A%222+%7C%7C+3%22%7D%2C%22peerDependenciesMeta%22%3A%7B%22%40vue%2Fcompiler-sfc%22%3A%7B%22optional%22%3Atrue%7D%7D%2C%22version%22%3A%224.3.1%22%7D%5D) `@babel/core`.
I am unfamiliar with Babel, so I apologize if just having it installed is doing something behind the scenes. If not, could `@babel/core` be removed?

**Comment by IanVS** [comment]
Good callout.  I think this is a holdover from the upstream we forked from.  We get the parser from `@babel/parser` instead of `@babel/core`, so I believe you're right that we can remove the dependency.  Would you like to submit a PR and we can try it out?

**Comment by cobaltt7** [comment]
Thanks for addressing this! Sorry I wasn't able to make a PR, I've been busy.

**Comment by cobaltt7** [comment]
Thank you!

**Comment by IanVS** [comment]
Thanks for bringing it up!  We'll try to get it released asap.
