### ISSUE TITLE
bug: this plugin seems to break Explicit Resource Management

### ISSUE THREAD

**Issue by KATT** [IanVS/prettier-plugin-sort-imports#193]
Seems to break explicit resource management

**Your Environment**

- ` "@ianvs/prettier-plugin-sort-imports": "^4.4.0"`
-   **Prettier version**: 3.3.3 (latest)
-   **node version**: 20.10.0
-   **package manager**: pnpm@9.12.2
-   **IDE**: terminal

**Describe the bug**

When using explicit resource management, this plugin seemingly breaks it

**To Reproduce**

1.

```sh
git clone git@github.com:trpc/trpc.git -b 11-01-using
cd trpc
pnpm i
pnpm prettier packages/tests/server/using.test.ts --write
```

2. Comment out https://github.com/trpc/trpc/blob/333f14aedff108be696d4fef71f184ba9c0d7cf6/prettier.config.js#L14
3. Run `pnpm prettier packages/tests/server/using.test.ts --write`

**Expected behavior**

It should work

**Screenshots, code sample, etc**

https://github.com/user-attachments/assets/7dd3dde0-2274-4490-aa39-7069f707c119

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**

```js
/** @typedef  {import("@ianvs/prettier-plugin-sort-imports").PluginConfig} SortImportsConfig*/
/** @typedef  {import("prettier").Config} PrettierConfig*/
/** @typedef  {{ tailwindConfig: string }} TailwindConfig*/

/** @type { PrettierConfig | SortImportsConfig | TailwindConfig } */
export default {
  printWidth: 80,
  trailingComma: 'all',
  endOfLine: 'auto',
  singleQuote: true,
  importOrder: ['___', '__', '<THIRD_PARTY_MODULES>', '^[./]'],
  tailwindConfig: './www/tailwind.config.ts',
  plugins: [
    '@ianvs/prettier-plugin-sort-imports',
    /**
     * Tailwind plugin must come last!
     */
    'prettier-plugin-tailwindcss',
  ],
};
```

**Error log**

```
SyntaxError: This experimental syntax requires enabling the parser plugin: "explicitResourceManagement". (11:2)
```
**Contribute to @ianvs/prettier-plugin-sort-imports**

-   [x] I'm willing to fix this bug 🥇

**Comment by KATT** [comment]
```diff
@@ -9,6 +9,7 @@ export default {
   endOfLine: 'auto',
   singleQuote: true,
   importOrder: ['___', '__', '<THIRD_PARTY_MODULES>', '^[./]'],
+  importOrderParserPlugins: ['typescript', 'jsx', 'explicitResourceManagement'],
   tailwindConfig: './www/tailwind.config.ts',
   plugins: [
     '@ianvs/prettier-plugin-sort-imports',
```

**Comment by KATT** [comment]
Alright, @juliusmarminge helped me, apparently the below was needed:

```diff
   importOrder: ['___', '__', '<THIRD_PARTY_MODULES>', '^[./]'],
+  importOrderParserPlugins: ['typescript', 'jsx', 'explicitResourceManagement'],
```

I'm surprised this is needed, but I don't know anything about how anything actually works in prettier plugins, so I guess this is normal. I'll close for now

**Comment by IanVS** [comment]
Glad you figured it out!  It's needed because this plugin uses babel to parse your code into an AST, find the imports, and manipulate them.  Babel's parser supports experimental JavaScript features through the use of plugins, which are listed here: https://babeljs.io/docs/babel-parser#plugins.

**Comment by KATT** [comment]
Does prettier without the plugin _not_ use babel then? 🤔

**Comment by IanVS** [comment]
It does use babel, and it doesn't specify any plugins, from what I can tell…

I'll be honest that this is a holdover from the original fork, and I've never loved having to specify these parser plugins.  I'll try to do some investigating when I get some time.
