### ISSUE TITLE
This plugin breaks explicitResourceManagement support in Prettier

### ISSUE THREAD

**Issue by jasikpark** [IanVS/prettier-plugin-sort-imports#194]
**Your Environment**

-   **Prettier version**: 4.0.0-alpha.10
-   **node version**: 20.16.0
-   **package manager**: pnpm@8
-   **IDE**: VScode

**Describe the bug**

Prettier supports `using x = y();` syntax via a babel plugin, but it sounds like this prettier plugin knocks that out.

**To Reproduce**

https://github.com/prettier/prettier/discussions/16186#discussioncomment-11206697

**Expected behavior**

Code containing `using x = y()` should not provide prettier errors

**Screenshots, code sample, etc**

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**

**Error log**

**Contribute to @ianvs/prettier-plugin-sort-imports**

-   [ ] I'm willing to fix this bug 🥇

**Comment by jasikpark** [comment]
IG this is a dupe of #193 / #182

**Comment by IanVS** [comment]
Yes, duplicate.
