### ISSUE TITLE
Plugin crashes on type import w/ same name as a global value

### ISSUE THREAD

**Issue by ethanresnick** [IanVS/prettier-plugin-sort-imports#31]
**Your Environment**

-   **Prettier version**: 2.6.2
-   **node version**: 16
-   **package manager**: npm 8.5.0
-   **IDE**: VSCode

**Describe the bug**

Following snippet causes prettier to fail on the file. It crashes with the error: `SyntaxError: Identifier 'X' has already been declared.`

**To Reproduce**

```
import { type X } from 'y';
const X = {};
```

```
// legal if X happens to be a type only.
import { X } from 'y';
const X = {};
```

**Expected behavior**

Should not crash.

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**

```json
{
  "trailingComma": "es5",
  "tabWidth": 2,
  "semi": true,
  "singleQuote": true,
  "importOrderSeparation": true,
  "importOrderSortSpecifiers": true,
  "importOrder": [
    "<THIRD_PARTY_MODULES>",
    "(.*)components/(.*)$",
    "^[./]"
  ]
}
```

**Contribute to @ianvs/prettier-plugin-sort-imports**

-   [ ] I'm willing to fix this bug 🥇

**Comment by IanVS** [comment]
Hi @ethanresnick, can you try adding `importOrderParserPlugins: ['typescript'],` to your prettier config?

**Comment by ethanresnick** [comment]
@IanVS Thanks for the fast response! I just tried adding that, but the error still occurs, unfortunately.

**Comment by fbartho** [comment]
Is that entirely legal typescript?

When I test that syntax, it crashes the TypeScript compiler: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzjAnmApnAGgJjgXzgDMoIQ4ByFCgbgChRJZFs9CSzKUda6Hxo8JKgzYCxUuSq86AYwgA7AM7wscALyJ8NIA

**Comment by ethanresnick** [comment]
> Is that entirely legal typescript?

One of the cases from my OP was not legal Typescript, so I've updated the OP to remove that case. Some other cases (which I've left in the OP) are legal though.

**Comment by ethanresnick** [comment]
Here's an example that uses a real module, to show it fully working in the playground: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFSgQwHYGcDGEAmApgKIZ77AYDmcAvnAGZQQhwDkGBhAXAEYCuDBoShsA3ACg82eKky4upcpRoBeRLUkSG-MjGAQMcYPgAUAfWAxuKdNnIkyBFQEpEEuJ7hRCMflCM5e0UnCmpJWiA

**Comment by IanVS** [comment]
This plugin uses the babel parser to generate an AST, then we modify the AST, and print it back out to source.  You seem to have stumbled upon a limitation of the babel parser, as seen in https://github.com/babel/babel/issues/10015.  If you check https://astexplorer.net/#/gist/37f431b33541330bd2ba87a720f85150/b19d62a18cd600add6d2787c4e650d950e982cbc, you'll see that the babel parser fails, but the typescript parser succeeds (as you also demonstrated above).  

So, unfortunately I don't think there's anything we can do in this project until the babel parser is updated.  Thanks for reporting, and I suggest you follow the babel issue for updates.

**Comment by ethanresnick** [comment]
That babel issue is unfortunate, but thanks for your quick help getting to the root of the issue!
