### ISSUE TITLE
Prettier fails with SyntaxError when using angle bracket types assertion

### ISSUE THREAD

**Issue by AceFire6** [IanVS/prettier-plugin-sort-imports#32]
**Your Environment**

-   **Prettier version**: 2.7.1
-   **node version**: v16.13.1
-   **package manager**: pnpm@7
-   **IDE**: CLI

**Describe the bug**

When running prettier against a file with [angle-bracket type assertions](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions) a SyntaxError is raised and prettier fails.

**To Reproduce**

```ts
// test.ts

type CountryCode = string & { __countryCode__: void };

const countryCode = <CountryCode>'ZA';
console.info(`Country code: ${countryCode}`);
```

Run: `prettier test.ts`

**Expected behavior**

Prettier to check the code without failing

**Screenshots, code sample, etc**

![Screenshot 2022-07-13 at 13 26 57](https://user-images.githubusercontent.com/4126778/178723329-9c0387ed-58c2-4d99-b5ed-f1bf3233c552.png)

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**

```
// .prettierrc.cjs
/**
 * Note: These settings also take into account the .editorconfig file
 *
 * @type {import('prettier').Config}
 */
module.exports = {
  printWidth: 80,
  singleQuote: true,
  endOfLine: 'lf',
  semi: true,
  plugins: [
    require.resolve('prettier-plugin-sh'),
    require.resolve('@ianvs/prettier-plugin-sort-imports'),
  ],
  // Empty strings denote separators
  importOrder: ['', '^@shared/(.*)$', '', '^src/(.*)$', '^[./]'],
  importOrderGroupNamespaceSpecifiers: true,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
};

```

**Error log**

```
test.ts[error] test.ts: SyntaxError: Unterminated JSX contents. (4:42)
[error]   1 | type CountryCode = string & { __countryCode__: void };
[error]   2 |
[error]   3 | const countryCode = <CountryCode>'ZA';
[error]   4 | console.info(`Country code: ${countryCode}`);
[error]   5 |
```

**Contribute to @ianvs/prettier-plugin-sort-imports**

-   [x] I'm willing to fix this bug 🥇

I am willing to fix this bug. I'd just need to be pointed in the right direction

**Comment by AceFire6** [comment]
I added this to my prettier config and it solved the issue
```ts
importOrderParserPlugins: ['typescript'],
```

**Comment by IanVS** [comment]
We will be working on better parser auto detection in an upcoming release, but for now this is indeed the correct fix.

**Comment by AceFire6** [comment]
Just a follow-up. We also have TSX in our repo so I needed to do this to properly support the `.tsx` and `ts` files.

```
// .prettierrc.cjs

module.exports = {
  printWidth: 80,
  singleQuote: true,
  endOfLine: 'lf',
  semi: true,
  plugins: [
    require.resolve('prettier-plugin-sh'),
    require.resolve('@ianvs/prettier-plugin-sort-imports'),
  ],
  // Empty strings denote separators
  importOrder: ['', '^@shared/(.*)$', '', '^src/(.*)$', '^[./]'],
  importOrderGroupNamespaceSpecifiers: true,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  overrides: [
    {
      files: '*.ts',
      options: {
        importOrderParserPlugins: ['typescript'],
      },
    },
  ],
};
```

**Comment by IanVS** [comment]
Thanks.  We're tracking the auto-detection feature in https://github.com/IanVS/prettier-plugin-sort-imports/issues/24.  I'm glad you got everything working though.
