### ISSUE TITLE
Conflicts with prettier-plugin-tailwindcss

### ISSUE THREAD

**Issue by mattiaz9** [IanVS/prettier-plugin-sort-imports#36]
**Your Environment**

-   **Prettier version**: 2.7.1
-   **node version**: 18.8
-   **package manager**: yarn@1.22.18
-   **IDE**: VScode

**Describe the bug**

It seems like this plugin is conflicting with `prettier-plugin-tailwindcss` and by uninstalling `prettier-plugin-sort-imports` it starts to work again.

**To Reproduce**
- yarn add -D prettier-plugin-tailwindcss
- yarn add -D @ianvs/prettier-plugin-sort-imports

**Expected behavior**

I expect the tailwind plugin to sort all my classes.

**Screenshots, code sample, etc**

Before installing prettier-plugin-sort-imports:
<img width="736" alt="Screenshot 2022-09-07 at 18 57 43" src="https://user-images.githubusercontent.com/9766700/188937580-c3d16342-b546-438f-bb68-3278c1031bc5.png">

After installing prettier-plugin-sort-imports:
<img width="742" alt="Screenshot 2022-09-07 at 19 04 01" src="https://user-images.githubusercontent.com/9766700/188937655-5cbd8cbf-1f92-4c29-af54-2bf89065dc08.png">

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**

```json
{
  "htmlWhitespaceSensitivity": "ignore",
  "printWidth": 100,
  "singleQuote": false,
  "semi": false,
  "useTabs": false,
  "proseWrap": "always",
  "arrowParens": "avoid",
  "bracketSpacing": true,
  "trailingComma": "es5",
  "importOrder": [
    "",
    "^react",
    "<THIRD_PARTY_MODULES>",
    "",
    ".s?css$",
    "^@heroicons",
    "^@/assets",
    "",
    "^[./]",
    "^@/",
    "",
    "<THIRD_PARTY_TYPES>",
    "<TYPE>"
  ],
  "importOrderSeparation": false,
  "importOrderMergeDuplicateImports": true,
  "plugins": [
    "prettier-plugin-tailwindcss",
    "@ianvs/prettier-plugin-sort-imports"
  ]
}
```

**Error log**

no errors

**Comment by IanVS** [comment]
Unfortunately this is a known issue since both plugins use some of the same APIs. You can read more, with some workarounds, in https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/9.

**Comment by mattiaz9** [comment]
@IanVS thanks for the info, but unfortunately that workaround isn't working for me

**Comment by IanVS** [comment]
How about this one? https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/31#issuecomment-1195411734

**Comment by mattiaz9** [comment]
@IanVS yes that worked, thank you! 🎉

**Comment by felixgren** [comment]
That fix didn't work for me due to 
`TypeError: Cannot read properties of undefined (reading 'map').` 

[This](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/9#issuecomment-1157359437) workaround solved it.


```jsx
const baseConfig = require('../../prettier.config.cjs');

const pluginSortImports = require('@ianvs/prettier-plugin-sort-imports');
const pluginTailwindcss = require('prettier-plugin-tailwindcss');

/** @type {import("prettier").Plugin}  */
const mixedPlugin = {
  parsers: {
    typescript: {
      ...pluginTailwindcss.parsers.typescript,
      preprocess: pluginSortImports.parsers.typescript.preprocess,
    },
  },
  options: {
    ...pluginSortImports.options,
  },
};

module.exports = {
  ...baseConfig,
  tailwindConfig: './tailwind.config.cjs',
  plugins: [mixedPlugin],
};
````
