### ISSUE TITLE
Imports with special regex are not moved to end group

### ISSUE THREAD

**Issue by obriankevin11** [IanVS/prettier-plugin-sort-imports#46]
Hi!

I'm having the following issue:
**Imports containing ".css" string are not moved to end group**

**Configuration**
-   **Prettier version**: 2.7.1
-   **node version**: 16.17.0
-   **package manager**: yarn@1.22.19
-   **IDE**: VScode

**To Reproduce**

tsx file:
```
import './test.css'
import '@lib/tables/dist/bla.css'
import * as React from 'react';
import { FormattedMessage } from 'react-intl';
import { Foo } from 'types/models'
```

.prettierrc
```
  "importOrder": [
    "(react|redux)",
    "(components|pages)/(.*)$",
    "<THIRD_PARTY_MODULES>",
    "(\\.css)"
  ],
  "importOrderBuiltinModulesToTop": true,
  "importOrderCaseInsensitive": true,
  "importOrderMergeDuplicateImports": true,
  "importOrderCombineTypeAndValueImports": true,
  "importOrderSeparation": true,
  "importOrderSortSpecifiers": true
```
**Result**
```
import './test.css';
import '@lib/tables/dist/bla.css';

import { Foo } from 'types/models';

import * as React from 'react';
import { FormattedMessage } from 'react-intl';
```

**Expected behavior**

```
import * as React from 'react';
import { FormattedMessage } from 'react-intl';

import { Foo } from 'types/models';

import './test.css';
import '@lib/tables/dist/bla.css';
```

Thank you!

**Comment by IanVS** [comment]
@obriankevin11 Could you try using `".css$",` as the pattern, instead of `"(\\.css)"`?

**Comment by fbartho** [comment]
I wonder if side-effect-only-imports are an edge case that isn’t being sorted fully?

**Comment by fbartho** [comment]
I think side-effect-imports might be assumed to have a purpose in a specific order?

**Comment by IanVS** [comment]
Oh, I missed that it was a side effect import. Yes, we do not sort side effect imports, since in general it is not safe to do so.

**Comment by obriankevin11** [comment]
ok I understand but is there a way to bypass side-effect-only-imports rule/restriction as I know it won't have side effects? it would be nice to have the choice :)

**Comment by IanVS** [comment]
No, sorry but there is not. You can use the `@trivago` plugin that this is forked from. It does not treat side effect nodes differently from others.
