### ISSUE TITLE
Astro files should be treated as side-effect imports

### ISSUE THREAD

**Issue by jasikpark** [IanVS/prettier-plugin-sort-imports#48]
**Your Environment**

-   **Prettier version**: 2.7.1
-   **node version**: 16.16.0
-   **package manager**: npm@8.15.0
-   **IDE**: VS Code

**Describe the bug**

When formatting imports in an Astro file, Astro component imports are treated as being interchangeable when the order that they are imported determines how Astro/Vite then bundles and loads the associated CSS.

**To Reproduce**

Run prettier + `@ianvs/prettier-plugin-sort-imports` + prettier-plugin-astro over an astro file;

See that the imports get sorted as regular imports && that changing the order of astro imports affect how the cascade is loaded

**Expected behavior**

Astro component imports are treated as equivalent to CSS imports like `import "./global.css";`, which means they would require manual sorting.

I'm not sure how you detect astro components that are exported from TS files in npm modules, or how you might mark an Astro file as allowed to be sorted

**Screenshots, code sample, etc**

ex:
<img width="653" alt="image" src="https://user-images.githubusercontent.com/10626596/202036240-c8fd59b0-ca7b-4bd9-8557-f025ddcfa1ba.png">

this diff caused CSS changes due to the `FullBleedLayout`, which imports global css, to below other component imports that depend on CSS rules set in that layout file.

maybe the solution would be to not set global css directly in a layout? or this should be a fix in astro?

`FullBleedLayout` imports `MainHead`, which imports:

```astro
---
import "@styles/global.scss";
import "@styles/fontawesome.scss";
...
```

stackblitz repro: https://stackblitz.com/edit/github-ryaymc?file=src/pages/index.md

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**

**Error log**

**Contribute to @ianvs/prettier-plugin-sort-imports**

-   [X] I'm willing to fix this bug 🥇

**Comment by fbartho** [comment]
So you're saying it's never permitted to sort astro file imports? 

If that's the case, that's pretty incompatible with a plugin called prettier-plugin-sort-imports, right?
----

Would it be acceptable to tell people that when they want side-effects in a specific order they need two copies of an import:

```typescript
// Side-effects in a specific order (won't be touched because they're clearly side effects)
import "@layouts/full-bleed.astro";
import "@atoms/FeatureDetails.astro";
import "@atoms/FeatureList.astro";
import "@atoms/CTABanner.astro";
import "@screens/index/EmailSignupSuccess.astro";
import "@screens/index/Hero.astro";

// Imports in any order, but will be sorted by this plugin:
import { getBgHeroCSS } from "@assets/getBgHeroCSS";
import Svg from "@jasikpark/astro-svg-loader";
import FeatureDetails from "@atoms/FeatureDetails.astro";
import FeatureList from "@atoms/FeatureList.astro";
import CTABanner from "@components/banners/CTABanner.astro";
import FullBleedLayout from "@layouts/FullBleed astro";
import EmailSignupSuccess from "@screens/index/EmailSignupSuccess.astro";
import Hero from "@screens/index/Hero.astro";
```

**Comment by jasikpark** [comment]
It sounds like this is only a problem for Astro components which import global css; similar to having a react component that imports and uses global css in a project that uses CSS Modules in most places...

I'm trying to figure out what the correct setup is here..

**Comment by jasikpark** [comment]
So maybe just slap a prettier ignore rule on the offending global style importing components?

**Comment by fbartho** [comment]
We've made some requests to upstream Prettier for specific improvements around plugins, but… yeah, this one might be an unlikely request.

Generally, I'd say if order-of-your-imports is sensitive, that you should have a comment on each line explaining that that's the case. So in our codebases this wouldn't be a big deal. (Though we'd definitely recommend against import-side-effects as a general practice).

**Comment by jasikpark** [comment]
i guess i might just configure the few global files to be sorted correctly in the config?

**Comment by jasikpark** [comment]
looks like 

```diff
importOrder:
  [
+    "^(.*)MainHead/MainHead.astro",
+    "^(.*)(layouts/)(.*)$",
    "^(@atoms/|@components/|@data/|@hooks/|@layouts/|@screens/|@scripts/|@styles/|@util/)(.*)$",
    "^(?!.*[.]css$)[./].*$",
    ".css$",
  ]
```

did the trick

**Comment by fbartho** [comment]
#success #resolved!
