### ISSUE TITLE
Option to remove unused imports

### ISSUE THREAD

**Issue by aleclarson** [IanVS/prettier-plugin-sort-imports#49]
The `codeActionsOnSave.organizeImports` setting in VSCode happens to remove unused imports. It would be great if this plugin had such an option.

**Comment by IanVS** [comment]
Hmmmm, I wonder if this is taking things just a step too far for a "formatter".  This is a significant change to the AST, more than just moving things around.  

I did come across https://www.npmjs.com/package/eslint-plugin-unused-imports though, which looks like it might do what you want?

@blutorange @fbartho what do you think?  Should this request be in-scope for this project?  Right now I'm leaning towards 👎.
