### ISSUE TITLE
prettier-ignore should not move the import line past code

### ISSUE THREAD

**Issue by KholdStare** [IanVS/prettier-plugin-sort-imports#50]
**Your Environment**

-   **Prettier version**: 2.7.1
-   **node version**: v14.18.1
-   **package manager**: yarn@3.1.1
-   **IDE**: [VScode, CLI]

**Describe the bug**

Imports are moved around code even with `// prettier-ignore`. The order relative to other imports is preserved, but code gets shoved below all the imports (or imports get shoved above code, depending on how you look at it). This can pop up when mocking some functionality that another module depends on. For example https://www.npmjs.com/package/firestore-jest-mock requires running `mockGoogleCloudFirestore` before any import of `@google-cloud/firestore`. See the `@google-cloud/firestore compatibility` section on the package page

**To Reproduce**

```
someCode();

// prettier-ignore
import * as fs from "node:fs";
```

**Expected behavior**

Any import line with `// prettier-ignore` should not budge, even relative to code.

**Screenshots, code sample, etc**

As an example from our codebase:

```typescript
mockGoogleCloudFirestore({
  database: {
    markets: [{ id: exampleBetMarket.marketAddress, ...exampleBetMarket }],
  },
});

// prettier-ignore
import { FirebaseUpdater, DocumentDBData, DocumentDB } from "./firebaseupdater";
```

becomes 

```typescript
// prettier-ignore
import { FirebaseUpdater, DocumentDBData, DocumentDB } from "./firebaseupdater";

mockGoogleCloudFirestore({
  database: {
    markets: [{ id: exampleBetMarket.marketAddress, ...exampleBetMarket }],
  },
});
```

**Contribute to @ianvs/prettier-plugin-sort-imports**

-   [ ] I'm willing to fix this bug 🥇

**Comment by IanVS** [comment]
@blutorange i think you may have looked into this at one time. If so, do you recall what the challenge was?

**Comment by villanuevadani** [comment]
Any progress on this topic?

**Comment by IanVS** [comment]
I don't see any mention in [npmjs.com/package/firestore-jest-mock](https://www.npmjs.com/package/firestore-jest-mock) about putting code before imports.  Technically, imports always run before any of the code in the module, so even if you put code above the imports, it will still run afterwards.  

I think the only way to achieve what you want is to use a dynamic `import()` statement so that you can run some code beforehand.
