### ISSUE TITLE
Line break removed when importOrderCombineTypeAndValueImports is used

### ISSUE THREAD

**Issue by andidev** [IanVS/prettier-plugin-sort-imports#54]
**Your Environment**

-   **Prettier version**: 2.7.1
-   **node version**: v16.17.0
-   **package manager**: npm@9.3.1
-   **IDE**: Webstorm

**Describe the bug**
Sorting imports with option `importOrderCombineTypeAndValueImports: true` removes a line break at top of prettier anotation if the type import is defined above import line it is merged with.

<img width="685" alt="image" src="https://user-images.githubusercontent.com/571389/226326229-3aae015c-acc2-42c8-9d29-4ca24bacf5f0.png">

becomes:
<img width="887" alt="image" src="https://user-images.githubusercontent.com/571389/226326266-ed646958-dda3-4b95-9de4-53d230514d2b.png">

**Expected behavior**
Expected a line break like this:
<img width="834" alt="image" src="https://user-images.githubusercontent.com/571389/226327456-19660845-1734-4c57-b659-a841d340f999.png">

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**

```
/**
 * @prettier
 */
module.exports = {
    printWidth: 200,
    tabWidth: 4,
    useTabs: false,
    semi: true,
    singleQuote: true,
    jsxSingleQuote: true,
    trailingComma: 'es5',
    arrowParens: 'avoid',
    requirePragma: true,
    bracketSpacing: true,
    quoteProps: 'consistent',
    parser: 'typescript',
    overrides: [
        {
            files: 'src/i18n/*.js',
            options: {
                printWidth: 20,
            },
        },
        {
            files: 'src/i18n/translate.js',
            options: {
                printWidth: 200,
            },
        },
    ],
    importOrder: ['<THIRD_PARTY_MODULES>', '^rootpath$', '^(scripts/.*)$', '(^src/.*)$', '^(test/.*)$'],
    importOrderSeparation: false,
    importOrderSortSpecifiers: true,
    importOrderBuiltinModulesToTop: true,
    importOrderMergeDuplicateImports: true,
    importOrderCombineTypeAndValueImports: true,
};

```

**Contribute to @ianvs/prettier-plugin-sort-imports**

-   [ ] I'm willing to fix this bug 🥇

**Comment by andidev** [comment]
Also noticed that this plugin (compared to original) does not remove new lines after the prettier pragma comment.
![image](https://user-images.githubusercontent.com/571389/227511163-0df8521d-c118-431d-8a09-161671ced4ff.png)
Like these line breaks are kept.
Not sure if this is intentional and in case this may help solve this issue by doing a last formatting at end with the first import.

**Comment by IanVS** [comment]
Thanks, I'll look into this as soon as I get some spare time, but it might be a little while.

**Comment by fbartho** [comment]
@andidev I don't believe this plugin *should* remove (all) new-lines after the pragma-comment -- even though the original plugin does so. -- You wouldn't want us to move that comment away from top-of-file if your currently-first import gets sorted lower down.

That said in #71 I've made significant changes to our handling of comments, so once that gets reviewed (and fixed if I made a mistake) your original bug report should no-longer be happening!

**Comment by andidev** [comment]
well the pragma comment should of course not be sorted lower. however removing the blank string at top if any would not harm according to me but I get this might be a taste what you like or not.
however the main thing with current version is that it adds a black line sometimes when sorting. 
if 71 solves that I am more than happy!

**Comment by IanVS** [comment]
Hi @andidev!  We've just released 4.0.0-alpha.4 which includes changes to the way we handle comments.  We have a [migration guide](https://github.com/IanVS/prettier-plugin-sort-imports/blob/next/docs/MIGRATION.md#migrating-from-v3xx-to-v4xx), but mostly we are becoming more opinionated on options to make the plugin easier to configure.  

We'd love if you were able to try it out and let us know what you think!

**Comment by andidev** [comment]
Wow nice work, like the changes!

However I cannot test this issue since
`importOrderTypeScriptVersion: '4.8.2',`
does not seem to work. Setting it I would seem to trigger the importOrderCombineTypeAndValueImports behaviour from old versions. @IanVS @fbartho 

Otherwise I tested it on our flow and typescript largest code bases and besides that it seem to work (however the imports where already sorted so not sure how much test branches this validates)

**Comment by IanVS** [comment]
@andidev yes, by default we will now combine type and value imports for versions of typescript that support that syntax.  If you'd rather keep type imports separate, and sorted to their own section, you can use the `<TYPES>` keyword in your `importOrder`.  You can also just not provide a typescript version, and the type and value imports will not be combined.  That is the only usage of that version setting at the moment.

**Comment by andidev** [comment]
@IanVS I think you misunderstood me. I know it is suppose to combine it by default but my problem is it does not combine it. Types and non types importer from same file is kept on separate rows.
And I have specified the correct ts version according to the migration guide.

**Comment by fbartho** [comment]
@andidev We have a test-case that verifies that we combine them here: https://github.com/IanVS/prettier-plugin-sort-imports/blob/eb1220adc0dbe3912ca961abf4527d19fa43bab2/tests/TypescriptModern/__snapshots__/ppsi.spec.ts.snap#L4-L16

If you want us to debug it further, I'd be happy to help -- please supply your sample code! (Ideally as a new ticket, with your prettier.config settings too)

**Comment by IanVS** [comment]
Oh okay, thanks for explaining!  A new issue would be great if you don't mind. Also note, it only works when you use `import type`, since we don't inspect the actual import itself to find out whether it's a value or import in the file where it is being exported.

**Comment by andidev** [comment]
So it looks like it my error was a webstorm doing the sorting instead of prettier (even though prettier is configured).

@IanVS 
But this issue is still not solved. I can reproduce it with following code:
```ts
/**
 * @prettier
 */
import type { FooValue } from './foo';
import { fooValue } from './foo';
```
formats to:
```ts
/**
 * @prettier
 */

import { fooValue, type FooValue } from './foo';
```

@fbartho 
I even found another case that is sorting it even worse (think its connected to this issue since probably the same implementation causing it):
```ts
/**
 * @prettier
 */
import { requireValue } from 'src/utils/require/requireValue';
import type { FooValue } from './foo';
import { fooValue } from './foo';
```

formats to:
```ts
import { fooValue, type FooValue } from './foo';
/**
 * @prettier
 */
import { requireValue } from 'src/utils/require/requireValue';
```

**Comment by IanVS** [comment]
Currently, we require one blank line after comments at the top of the page in order to "detach" them from the following import statement. If you have a comment directly above an import, we treat it as a leading comment of that import, and it will move with the import if it gets sorted.

Personally, I prefer having a blank line separating comments, pragma, or directives at the top of the page, but I realize not everyone might. Unfortunately in this case it's just something that we need to be opinionated about so that we can have predictable behavior.

**Comment by andidev** [comment]
@IanVS its not solved. Its the first example I mentioned in my comment is this issue.
new line or now new line after prettier import does not matter I think, but adding a new line in some case just because two imports are moved does not make sense.
Also as in the comment there seem to be some sorting issue causing an import to be moved above the prettier comment which breaks the prettier formatting of file. This one I would say is critical with the new release, just tested and this does not happen in old version.

**Comment by IanVS** [comment]
```ts
/**
 * @prettier
 */
import type { FooValue } from './foo';
import { fooValue } from './foo';
```

Reformatting to 

```ts
/**
 * @prettier
 */

import { fooValue, type FooValue } from './foo';
```

Is not a bug, that's desired behavior.  

I can see why the second example you gave could be a problem, though.  I think we can find a way to deal with that case.

**Comment by andidev** [comment]
Ok, then it's just a strange behavior for a code formatter then. Because it formats a new line in case an import is merged to another if it's after the top comment. But in case the import sorted there is not merged with another import line it does not format a space. 

We formatted our whole code base and that is where I saw we sometimes got a new line after prettier comment and sometimes not. Just seemed strange. But it's an minor esthetic issue or maybe I am missing something so not gonna argue for it to be honest. 

Either way I appreciate the work on this import sorter!
Thanks! It helps us a lot reducing and simplifying import related merge conflicts.

**Comment by IanVS** [comment]
Thanks for your input, and I'm glad this is useful to you.  We're going to try making a change so that comments above the first import never move, and I'll see what we can do about the addition of that extra newline as well.

**Comment by IanVS** [comment]
@andidev would you mind trying 4.0.0-alpha.5?  We made some changes to better preserve comments at the tops of files.

**Comment by andidev** [comment]
@IanVS 
lgtm, only thing I noticed was this case adds a new line
```ts
/**
 * @prettier
 */
import { requireValue } from 'src/utils/require/requireValue';
import type { FooValue } from './foo';
import { fooValue } from './foo';
```

formats to 
```ts
/**
 * @prettier
 */

import { fooValue, type FooValue } from './foo';
import { requireValue } from 'src/utils/require/requireValue';
```

but original issue seems to be solved actually and also formatting 
```ts
/**
 * @prettier
 */
import type { FooValue } from './foo';
import { fooValue } from './foo';
```
mentioned earlier formats correctly now without a line break.

**Comment by IanVS** [comment]
Thanks, we had a bug, https://github.com/IanVS/prettier-plugin-sort-imports/releases/tag/v4.0.0-alpha.6 should fix that for you now.  Sorry for the back-and-forth, but thanks for testing out the alphas!

**Comment by andidev** [comment]
nice just upgraded and tested it and cannot find any case yet causing empty lines or removed ones. 
Great work!
