### ISSUE TITLE
Support for compound classes?

### ISSUE THREAD

**Issue by DestroyerXyz** [IanVS/prettier-plugin-sort-imports#55]
**Is your feature request related to a problem?**
If I need to combine 2 or more classes in the same element, the order doesn't get parsed or fixed.
```js
// Using shadcn's cn utility
<div className={cn("flex-col bg-slate-800 h-screen w-screen flow-root", inter.className)}>

// Simple combination
<div className={"flex-col bg-slate-800 h-screen w-screen flow-root" + inter.className}>
```

**Describe the solution you'd like**
The classes get parsed just like regular ones.

**Describe alternatives you've considered**
N/A

**Comment by IanVS** [comment]
Hi @DestroyerXyz, this package has nothing to do with class names, it is for organizing the `import` statements at the top of a file.

**Comment by IanVS** [comment]
Haha no worries!
