### ISSUE TITLE
Unnecessary line breaks when importOrderSeparation feature is enabled

### ISSUE THREAD

**Issue by itsjavi** [IanVS/prettier-plugin-sort-imports#58]
**Your Environment**

-   **Prettier version**: 2.8.7
-   **node version**: 18.15.0
-   **package manager**: pnpm@8.1.0
-   **IDE**: PHPStorm 2022.3.3

**Describe the bug**
Under certain situations (like in the screenshot), extra unnecessary empty lines are added in PHPStorm when importOrderSeparation feature is enabled.

**To Reproduce**

1. enable importOrderSeparation or add empty strings in the  importOrder array
2. Enable "Run prettier on save" and/or "Run prettier on reformat code" in PHPStorm
  - It doesn't matter if "ESLint fix on save" is enabled or not
4. Reformat code and save

**Expected behavior**

No unnecessary new lines should appear.

**Screenshots, code sample, etc**

![image](https://user-images.githubusercontent.com/122741/229108561-b3b65a2c-f620-4e81-b61f-79d30e67ad0b.png)

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**

```json
// .prettierrc
{
  "semi": false,
  "printWidth": 100,
  "trailingComma": "es5",
  "tabWidth": 2,
  "singleQuote": true,
  "arrowParens": "avoid",
  "jsxSingleQuote": false,
  "plugins": [
    "@ianvs/prettier-plugin-sort-imports"
  ],
  "importOrderSeparation": true,
  "importOrder": [
    "^[Rr]eact(.*)$",
    "^@?next(.*)$",
    "^@app/(.*)$",
    "^@/(.*)$",
    "^[./]"
  ],
  "importOrderBuiltinModulesToTop": true,
  "importOrderCaseInsensitive": true,
  "importOrderParserPlugins": [
    "typescript",
    "jsx",
    "decorators-legacy"
  ],
  "importOrderMergeDuplicateImports": true,
  "importOrderCombineTypeAndValueImports": true,
  "importOrderSortSpecifiers": false
}
```

```json
// .eslintrc.json
{
  // "extends": ["next", "turbo", "next/core-web-vitals", "prettier"],
  "extends": ["next", "turbo", "next/core-web-vitals", "prettier"],
  "plugins": ["react-hooks"],
  "rules": {
    // "@next/next/no-html-link-for-pages": "off",
    // images
    "@next/next/no-img-element": "warn",
    "jsx-a11y/alt-text": "error",
    // components
    "react-hooks/exhaustive-deps": "off",
    "react-hooks/rules-of-hooks": "error",
    "react/jsx-key": "error",
    "react/no-unescaped-entities": "off"
  }
}
```

**Comment by itsjavi** [comment]
It seems more an IDE issue when "Optimize Imports" is enabled when reformatting code.
I think it can be closed

**Comment by IanVS** [comment]
Thanks for reporting back!
