### ISSUE TITLE
Astro export const prerender statment sort at top

### ISSUE THREAD

**Issue by pijusz** [IanVS/prettier-plugin-sort-imports#68]
**Is your feature request related to a problem?**
There is no way to sort some values at the very top. F.e. Astro "export const prerender = true;"

**Describe the solution you'd like**
I want some statements that are 'not-an-import' to be sorted at the very top.

**Additional context**
Astro Example From:
```javascript
---
import Layout from "~/layouts/Layout.astro";
import Testimonials from "~/components/Testimonials.astro";

import "~/styles/theme.scss";

export const prerender = true;
---
...
```

Astro Example To:
```javascript
---
export const prerender = true;

import Layout from "~/layouts/Layout.astro";
import Testimonials from "~/components/Testimonials.astro";

import "~/styles/theme.scss";
---
...
```

**Comment by fbartho** [comment]
My gut response that this is out-of-scope for this plugin, we don't look for arbitrary variable AST nodes. This might be something that would be better designed as a dedicated Astro Prettier Plugin, but it might be messy to do inside of this plugin.

**Comment by IanVS** [comment]
Thanks for the suggestion, @pijusz.  However, I agree with @fbartho, I don't think this is the right tool to do what you want.  This plugin is only for sorting imports.  You'd probably want to make your own prettier or eslint plugin to move that particular export (it could probably be a very simple plugin).

**Comment by IanVS** [comment]
I guess with the one caveat, if you have this

```astro
---
export const prerender = true;

import Layout from "~/layouts/Layout.astro";
import Testimonials from "~/components/Testimonials.astro";

import "~/styles/theme.scss";
---
```

Is this plugin moving it from the top and turning it into 

```astro
---
import Layout from "~/layouts/Layout.astro";
import Testimonials from "~/components/Testimonials.astro";

import "~/styles/theme.scss";

export const prerender = true;
---
```

If so, I would consider that a bug, and we can probably address it to only sort the imports and not move them.

**Comment by jasikpark** [comment]
i think that's the issue they had..

**Comment by jasikpark** [comment]
it is nice that the sorter moves all static imports to the top though

**Comment by jasikpark** [comment]
"constant exports come first" 🤔

**Comment by IanVS** [comment]
OK I can confirm that we do move the `export` to the bottom in the example I gave.  But it seems strange that Astro would require the export to come at the top, especially given that imports are always processed first before the rest of the file, which is why it's good practice to put imports at the top of the file, to avoid confusion.  

I'm not convinced whether this is a bug on our side or desired behavior, will need to investigate further.

**Comment by IanVS** [comment]
I don't see anything in the Astro docs saying it needs to be at the top of the file: https://docs.astro.build/en/guides/server-side-rendering/#hybrid-rendering...

**Comment by IanVS** [comment]
>It's a stylistic recommendation from Astro.

I don't see where Astro even recommends it to be at the top.  Do you have a link?  I looked through their discord as well, and didn't see mention of it being before imports.

**Comment by fbartho** [comment]
Hah! I don't use astro, I just scanned over the project in my normal research a year or more back.

I definitely should have clarified that I'm *interpreting* this as a stylistic convention. I just witnessed a bunch of basic hello-world code that had that in common.

I didn't mean to express that I had authoritative information on the topic! Sorry if I caused confusion.

**Comment by jasikpark** [comment]
<img width="897" alt="image" src="https://user-images.githubusercontent.com/10626596/234389946-940a0f2e-ef13-418b-94fa-d7ff0f1c109d.png">
confirmation from the @natemoo-re himself 😁 

this is just an aesthetic choice 👍

**Comment by natemoo-re** [comment]
Chiming in from the Astro team: I don't think I've ever seen `export const prerender = true` at the top of the file? At the very least, it's not a requirement (or explicit recommendation) from our side.

> My gut response that this is out-of-scope for this plugin, we don't look for arbitrary variable AST nodes. This might be something that would be better designed as a dedicated Astro Prettier Plugin, but it might be messy to do inside of this plugin.

You're definitely welcome to suggest this as an issue on the [`prettier-plugin-astro`](https://github.com/withastro/prettier-plugin-astro) repo @pijusz! I'm not sure if we'll end up implementing it since it's just an aesthetic choice, but maybe folks would like the option.
