### ISSUE TITLE
Improve default `importOrder`

### ISSUE THREAD

**Issue by IanVS** [IanVS/prettier-plugin-sort-imports#76]
**Is your feature request related to a problem?**
Currently, the default `importOrder` that we ship is kind of worthless, and only sorts everything alphabeteically.

**Describe the solution you'd like**
As discussed in https://github.com/IanVS/prettier-plugin-sort-imports/issues/22, let's make the default order be:

```js
importOrder: [
	// builtins (already happens no matter what the `importOrder` is set to)
	'<THIRD_PARTY_MODULES>',
	'^[./]', // Relative (local) imports
]
```

**Describe alternatives you've considered**

We could get fancier, but I think this is a sane default that most users will benefit from, and they're able to customize it further if they want.

**Comment by fbartho** [comment]
Right now, our default is `[]` -- but, we automatically inject built-ins to all queries (not-user-controllable), and then we automatically inject THIRD_PARTY_MODULES if it's not present somewhere in the list.

So are effective default is already as you described:
```js
[
	// builtins (already happens no matter what the `importOrder` is set to)
	'<THIRD_PARTY_MODULES>'
	// Implicit "everything else"
]
```

I think that means this ticket is moot!
<hr/>
I think someone could convince me that we need to let users write all the regexes they want, to do something like:
```js
[
  '<BUILT_INS>', // should we add special word?
  '@*', // Namespaced packages regex
  '^[^.]', // Non-local-imports
  '^[.], // All local imports
]
// Notice how there's no '<THIRD_PARTY_MODULES>' anywhere?
```

**Comment by fbartho** [comment]
I think we forgot to discuss the impact of removing `importOrderSeparation` on https://github.com/IanVS/prettier-plugin-sort-imports/issues/76

I think our default sort-order should be:

```
[
  built-ins, // 1
  "", // 2
  "<THIRD_PARTY_MODULES>", // 3
  "", // 4
  "^[^.]", // 5  -- absolute imports
  "", // 6 -- Should we have a gap?
  "^[.]", // 7 -- relative imports 
]
```
What do you think? should I remove all the gaps? just no-gap in step 6?

We could simplify our defaults by deleting 5-7, and having the new step 5 be `".*" // everything else` but we run the risk that absolute imports are alpha sorted below relative imports. `"./this/is/relative" < "apps/absolute/path" === true`

**Comment by IanVS** [comment]
The previous default was not to add spaces between imports, and users had to opt in with `importOrderSeparation`.  I think we should keep that same general idea, whereby the default is not to add spaces between import groups, and only sort them.  Users can add explicit gaps where they want by specifying them in their `importOrder`, and we can give some examples of common patterns in the README, which users can copy and use.  

Currently, if no `importOrder` is provided, this is what I get:

```js
exports[`defaults.js - babel-verify > defaults.js 1`] = `
import c from "./c"
import b from  "../b"
import a from "../../a"
import foo from 'foo';
import bar from 'bar';
import fs from 'fs';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
import fs from "fs";
import a from "../../a";
import b from "../b";
import c from "./c";
import bar from "bar";
import foo from "foo";

`;
```

Note that the "third party" imports are placed after relative imports.  I think we should prevent that, by using:

```js
[
  // built-ins (We can make this a special word in the future if people ask for it, but I don't think we have to right now),
  "<THIRD_PARTY_MODULES>",
  "^[.]", // relative (local) imports
]
```
